kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-egress-other-tenant-ns
  namespace: tenant1-ns1
spec:
  podSelector: {}
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            knative.dev/tenant: tenant1
  policyTypes:
    - Egress
