apiVersion: v1
kind: Pod
metadata:
  name: ping-tenant2-ns1-fail
  namespace: tenant1-ns1
spec:
  containers:
    - name: ping
      image:  docker.io/villardl/ping
      env:
        - name: TARGET
          value: "http://pong.tenant2-ns1:8080"
