apiVersion: v1
kind: Service
metadata:
  name: pong
  namespace: tenant1-ns2
spec:
  selector:
    app.kubernetes.io/name: pong
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
