kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: knative
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 31080
      listenAddress: 127.0.0.1
      hostPort: 80
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16
