kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-all # TODO: should allow only kourier to activator
  namespace: knative-serving
spec:
  podSelector: {}
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress
