apiVersion: v1
kind: Pod
metadata:
  name: ping
  namespace: tenant1-ns2
spec:
  containers:
    - name: ping
      image:  docker.io/villardl/ping
      env:
        - name: TARGET
          value: "http://pong.tenant1-ns2:8080"
